### ISSUE TITLE
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exceptio

### ISSUE THREAD

**Issue by ghost** [Shreykhanna/TelegramBot-PizzaOrderBot#1]
hello,
everytime i send /start it replies with an error as you in the picture below:
![image](https://user-images.githubusercontent.com/45691910/100617686-c4da4980-3312-11eb-870c-dfa0d247adc5.png)

**Comment by niranjanneeru** [comment]
@Mr4FX  Probably You are using a newer version of the python telegram bot package

```python3
#register this command
#update has all data regarding the newest message or change\
# context has the bot object which could be used to message and all those stuff 

def start(update, context):
         chat_id = update.message.chat.id
         message = "Hi I am using v13 of the library"
         context.bot.send_message(chat_id= chat_id,text=message) 
```

**Comment by niranjanneeru** [comment]
> @Mr4FX Probably You are using a newer version of the python telegram bot package
> 
> ```python
> #register this command
> #update has all data regarding the newest message or change\
> # context has the bot object which could be used to message and all those stuff 
> 
> def start(update, context):
>          chat_id = update.message.chat.id
>          message = "Hi I am using v13 of the library"
>          context.bot.send_message(chat_id= chat_id,text=message) 
> ```

This Project is 3 years old, I am making a new one will try to release it soon
